language: cpp

os:
  - linux
  - osx

compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - libcurl4-openssl-dev
      - libpthread-stubs0-dev
  homebrew:
    packages:
      - gcc@7
      - curl-openssl

before_script:
  - export CC="$(which -- gcc-7)" CXX="$(which -- g++-7)"
  - if [ ${TRAVIS_OS_NAME} = "osx" ]; then ln -s /usr/local/opt/openssl/include/openssl /usr/local/include; fi
  - mkdir -p ${TRAVIS_BUILD_DIR}/vendor/sqlite/build && cd ${TRAVIS_BUILD_DIR}/vendor/sqlite/build && cmake -D BUILD_SHARED_LIBS=1 ..
  - cd ${TRAVIS_BUILD_DIR}/vendor/sqlite/build && make

script:
  - mkdir -p ${TRAVIS_BUILD_DIR}/build && cd ${TRAVIS_BUILD_DIR}/build && cmake -D BUILD_SHARED_LIBS=1 -D CMAKE_BUILD_TYPE=Debug -D COUNTLY_BUILD_TESTS=1 -D COUNTLY_USE_SQLITE=1 ..
  - cd ${TRAVIS_BUILD_DIR}/build && make
  - ${TRAVIS_BUILD_DIR}/build/countly-tests -s
